### ISSUE TITLE
`java.lang.NoSuchMethodError` on Compose 1.7.0-beta06

### ISSUE THREAD

**Issue by mak1nt0sh** [composablehorizons/composables-core#5] opened 2024-07-31 14:37 UTC
Just trying out simple ModalBottomSheet and get this exception thrown.

```
    ModalBottomSheet(state = rememberModalBottomSheetState(initialDetent = SheetDetent.FullyExpanded)) {
        Sheet(
            modifier = modifier
                .fillMaxWidth()
                .widthIn(max = 600.dp)
        ) {
            Column(
                modifier = modifier
                    .fillMaxWidth()
                    .height(400.dp)
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    SheetDragHandle()
                    Text(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 16.dp),
                        text = "title"
                    )
                }
            }
        }
    }
```

```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function0;Landroidx/compose/animation/core/AnimationSpec;Lkotlin/jvm/functions/Function1;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/compose/foundation/gestures/AnchoredDraggableState; or its super classes (declaration of 'androidx.compose.foundation.gestures.AnchoredDraggableState' appears in /data/app/base.apk)
                                                                                                    	at com.composables.core.BottomSheetState.<init>(BottomSheet.kt:152)
                                                                                                    	at com.composables.core.BottomSheetKt.rememberBottomSheetState$lambda$3(BottomSheet.kt:89)
                                                                                                    	at com.composables.core.BottomSheetKt.$r8$lambda$kKoSsIJuqDp1LOEEnMzteF7Eu2k(Unknown Source:0)
                                                                                                    	at com.composables.core.BottomSheetKt$$ExternalSyntheticLambda6.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:89)
                                                                                                    	at com.composables.core.BottomSheetKt.rememberBottomSheetState(BottomSheet.kt:81)
                                                                                                    	at com.composables.core.ModalBottomSheetKt.Sheet(ModalBottomSheet.kt:173)
```

**Comment by alexstyl** [comment] 2024-07-31 18:40
Which version of Compose are you using?

Also which OS are you using Compose on? (ie Android - API 34)

**Comment by mak1nt0sh** [comment] 2024-07-31 18:44
Latest beta `1.7.0-
beta06` on Android only project.

**Comment by alexstyl** [comment] 2024-07-31 19:33
I tried using Compose `1.7.0-beta06` and it does indeed crash with the same stacktrace. Currently looking what is special with that version.

In the meantime, you can use the latest stable Compose release `1.6.8`

**Comment by mddanishansari** [comment] 2024-08-01 07:28
@alexstyl  
This is breaking because the definition of `AnchoredDraggableState` was changed in `Compose Foundation 1.7.0-alpha01` as they introduced `decayAnimationSpec` paramater and changed `animationSpec` parameter to `snapAnimationspec`

> API Changes
> - Introduce DecayAnimation in AnchoredDraggable, this change adds a decayAnimationSpec parameter to AnchoredDraggable allowing to use decay animation when settling to one of the anchors. The change also includes renaming the existing animationSpec to snapAnimationSpec to help understanding the use case of each spec.

Source: https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-alpha01

**Comment by alexstyl** [comment] 2024-08-01 09:59
Closing this as fixed at https://github.com/composablehorizons/composables-core/commit/86b675f1738d3ae018ba75ebd01486db7451c939

Will be released as part of `1.9.0`. Will share here when the version is published.

**Closed by alexstyl** 2024-08-01 09:59 UTC

**Comment by mddanishansari** [comment] 2024-08-01 10:08
@alexstyl now that we are on this topic, they have also deprecated `IndicationInstance` and `rememberUpdatedInstance`  which affects `FocusRingIndication` and they have suggested to move towards `IndicationNodeFactory` which uses `Modifier.Node` API

> New Features
> - Added a new Indication API, IndicationNodeFactory. This leads to more performant Indication implementations compared to the previous (now deprecated) rememberUpdatedInstance API. For migration information, see [developer.android.com](http://developer.android.com/).

**Comment by alexstyl** [comment] 2024-08-01 10:42
@mddanishansari thanks for letting me know. Unless this is breaking anything, it will be lower priority for now.

Could you kindly open a new issue about it? Copy pasting your message and the link to the migration would be fantastic.

**Comment by alexstyl** [comment] 2024-08-01 13:46
Shipped in [version 1.9.0](https://github.com/composablehorizons/composables-core/releases/tag/1.9.0)

**Comment by alexstyl** [comment] 2024-11-25 17:20
@TepesLucian need more info. can you confirm that the code of the OP's post is giving you the same stack trace on Android only?

**Comment by TepesLucian** [comment] 2024-11-26 15:42
```
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function0;Landroidx/compose/animation/core/AnimationSpec;Landroidx/compose/animation/core/DecayAnimationSpec;Lkotlin/jvm/functions/Function1;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/compose/foundation/gestures/AnchoredDraggableState; or its super classes (declaration of 'androidx.compose.foundation.gestures.AnchoredDraggableState' appears in /data/app/~~oNy348mAOgdSFPflHFliag==/com.x.y.z-LrJmhEfwZDuVcA0oX9CIrw==/base.apk)
    	at com.composables.core.BottomSheetState.<init>(BottomSheet.kt:160)
    	at com.composables.core.BottomSheetKt.rememberBottomSheetState$lambda$17(BottomSheet.kt:85)
    	at com.composables.core.BottomSheetKt.$r8$lambda$HOlp03M64Z9EpLpUe6obdQw4518(Unknown Source:0)
    	at com.composables.core.BottomSheetKt$$ExternalSyntheticLambda12.invoke(D8$$SyntheticClass:0)
```
So not quite the same crash.

**Comment by alexstyl** [comment] 2024-11-26 15:48
Could you kindly open a new issue for it? Hard to prioritize otherwise.

Copy paste your stacktrace with some code to reproduce if any.
